### ISSUE TITLE
use systemd instead of init.d script

### ISSUE THREAD

**Issue by wwannemacher** [sonatype-nexus-community/nexus-repository-installer#1]
Both redhat and debian distros are all moving toward systemd.

Although you can use systemd commands to control rc.d scripts, there are added features in systemd related to viewing logs, restarting the process on failure as well as the ability for services to start concurrently.

**Comment by bhamail** [comment]
Fixed in: ef0d04c57566031728e377d1193d8e7135b9c28c

Also fixed in IQ Server installer: https://github.com/sonatype-nexus-community/nexus-iq-server-installer/commit/4bf562305f3ad4b4536ca73d11b5f8bff869f1fa

By the way, you'll need to wait for the next release of these products to see the shiny new installer changes. If you can't wait for that, you could always build the installer yourself. :)
