### ISSUE TITLE
Can't update the APT repo due to invalid key

### ISSUE THREAD

**Issue by maicol07** [sonatype-nexus-community/nexus-repository-installer#20]
Key isn't valid:

```
Error: 21 https://repo.sonatype.com/repository/community-apt-hosted bionic InRelease
   The following signatures were invalid: EXPKEYSIG 964B5E720AA4F31A Sonatype Community <community-group@sonatype.com>
Reading package list ... Done
W: GPG Error: https://repo.sonatype.com/repository/community-apt-hosted bionic InRelease: The following signatures were invalid: EXPKEYSIG 964B5E720AA4F31A Sonatype Community <community-group@sonatype.com>
E: The repository "https://repo.sonatype.com/repository/community-apt-hosted bionic InRelease" is unsigned.
```

**Comment by maicol07** [comment]
I've parsed the key and it seems it has expired on August 14:
```
Valid until: Sat Aug 14 2021 04:13:20 GMT+0200 (CET)
```

**Comment by bhamail** [comment]
@maicol07 Thanks so much for reporting this, and digging into the root cause!

I'm working with our ops team to get the key updated. It should be updated now.

My solution was to download the new key file and "re-install" it via "Step 2" [here](https://github.com/sonatype-nexus-community/nexus-repository-installer#apt-setup). After re-installing the new key, my `apt update` worked fine.

That said, I'd like to update our initial setup instructions to maybe avoid a pitfall I just found: If you left the old key file on disk, then later "re-download" the new key file (to fix a key expiration problem), then you "might" accidentally download the new key file into a new name. If you are not careful, you might find yourself 're-installing' the old (expired) key file. You could chase your tail like this until you realize the new key file downloaded to a new file name....(`sudo apt-key add DEB-GPG-KEY-Sonatype.asc`) (don't ask me how long it took me to figure this out). ;)

**Comment by maicol07** [comment]
@bhamail that is pretty simple, if you specify the file name to wget:

```shell
wget -O DEB-GPG-KEY-Sonatype.asc https://repo.sonatype.com/repository/community-hosted/pki/deb-gpg/DEB-GPG-KEY-Sonatype.asc
```

**Comment by bhamail** [comment]
@maicol07  I like it! Feel like putting in a PR with the change? ;)
