### ISSUE TITLE
repository GPG public key expired

### ISSUE THREAD

**Issue by ViliusS** [sonatype-nexus-community/nexus-repository-installer#27]
https://repo.sonatype.com/repository/community-hosted/pki/rpm-gpg/RPM-GPG-KEY-Sonatype.asc repository GPG public key and probably https://repo.sonatype.com/repository/community-hosted/pki/deb-gpg/DEB-GPG-KEY-Sonatype.asc needs renewal. They have expired on 2021-08-15.

**Comment by BluCobalt** [comment]
I have the same issue
```
...
Importing GPG key 0x0AA4F31A:
 Userid     : "Sonatype Community <community-group@sonatype.com>"
 Fingerprint: E778 88C7 6714 EBD7 1940 25EA 964B 5E72 0AA4 F31A
 From       : https://repo.sonatype.com/repository/community-hosted/pki/rpm-gpg/RPM-GPG-KEY-Sonatype.asc
Is this ok [y/N]: y
Key imported successfully
warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
Import of key(s) didn't help, wrong key(s)?
Problem opening package nexus-repository-manager-3.43.0_01-1.el7.noarch.rpm. Failing package is: nexus-repository-manager-3.43.0_01-1.el7.noarch
 GPG Keys are configured as: https://repo.sonatype.com/repository/community-hosted/pki/rpm-gpg/RPM-GPG-KEY-Sonatype.asc
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
...
```

**Comment by ViliusS** [comment]
@BluCobalt I believe your issue will be fixed after another version release, which will use this fix https://github.com/sonatype-nexus-community/nexus-repository-installer/pull/26
This issue is about GPG key itself.

**Comment by BluCobalt** [comment]
I see now. EL9 stopped supporting SHA1 which is why this doesn't work. Do you know what I should do until the next release?

**Comment by ViliusS** [comment]
You can temporarily enable SHA1 support with `update-crypto-policies --set LEGACY` after install set it back `update-crypto-policies --set DEFAULT`

**Comment by BluCobalt** [comment]
Works, thanks!

**Comment by bhamail** [comment]
Still looking into things, but I have an unsubstantiated theory at this point: The expired GPG public keys in `community-hosted/pki` are not causing installation problems. 

I think those keys are only used if the published signing key for an .rpm can not be found. Since the updated GPG key used to sign the .rpm is published, the expired GPG key from `community-hosted/pki` does not come into play.

It's still probably worth uploading those `community-hosted/pki` keys to newer (unexpired) versions, but I think that work is lower priority. I may also hold off on updating the repo level keys until after a new version of Nexus Repository Manager (or IQ Server) is released - which will help verify if the expired repo level keys are actually causing issues.

**Comment by ViliusS** [comment]
For what it's worth, I don't believe expired GPG keys will cause installation issues. It's just a best practice to have them rotated as one of the signals that repository is operational and taken care of.
